	Then I should see "Listing samples"
	When I follow "Refresh"
	Then I should see "New sample"
	When I follow "New Article"
	Then I should see "New article"
	When I follow "Ajax Entry"
	Then I should see "Listing entries"
	When I follow "Edit Password"
	Then I should see "Edit Your Password"
	When I follow "Logout"
	Then I should see "user successfully logged out"